### ISSUE TITLE
IE6: Compatibility Issues with `.menu` and `.panel`

### ISSUE THREAD

**Issue by am01264** [am01264/oocss#2]
In some circumstances, this library fails in IE6 and lower versions. In particular, one setup of `.menu` has issues, and `.panel` doesn't work at all.

Because this relates to an archaic, and very dead browser... this will never be integrated into the main library. However, if you've been tasked with the thankless job of developing for those browsers, here's the solution:

## `.menu` has minor issues
Only applies when you're not also applying `.menu-vertical` or `.menu-float`, they work fine.

1. When applied to `<ul>` or `<ol>` a left-margin remains
2. `.menu-item` shows as inline.

### Fix

1. Set `margin-left` property to 0 (specific to IE6 and below)
```css
.menu {

    /* Bugfix:
     * IE6 and below have a default `margin-left` instead of `padding-left` for lists
     * Set `margin-left` property to 0
     */
    margin-left: 0;
}
```

2. As `inline-block` doesn't exist for IE6 and below, do the following:
```css
/* Bug Fix:
 * IE6 and below don't recognise `inline-block`
 * Here's the workaround:
 */
.menu-item {
    /* Pretend we're inline */
    display: inline;
    
    /* Force block rendering for children */
    zoom: 100%;
}
```

## `.panel` doesn't work

`.panel` normally works by creating a Block Formatting Context (see the CSS 2.1 spec for more information) using the `overflow` property. This is how in 2-lines of CSS, it both clears any floats and gives you a flexible width container for free.

Unfortunately, IE6 and below don't have a side-effect free fix. The closest is the following:

```css
.panel {

    /* Bug Fix:
     * `overflow: hidden` doesn't exist on IE6 or below
     * Warning: This will also cut off any overflowing content 
     */
    overflow: none;
}
```
